#!/usr/bin/env bash
# tune-nic-eno1.sh
# Reduziert Softirq-/Queue-Bottleneck auf eno1 wenn der lokale NFS-Client
# parallel zu anderen Diensten (z.B. Komandorr-HTTP-Polls) hohe Last erzeugt.
#
# Wirkung:
#   1. Verteilt eingehende Pakete via RSS (Hardware) oder RPS (Software)
#      auf alle Cores statt nur den NIC-IRQ-Core.
#   2. Vergroessert RX-/TX-Ring-Buffer auf Hardware-Maximum.
#   3. Setzt fq_codel statt fq als qdisc -> AQM bremst Bulk-NFS-Flows,
#      sodass kurze HTTP-Probe-Flows nicht verhungern.
#   4. Erhoeht netdev-Backlog und sock_flow_entries fuer hohe pps.
#
# Persistent:
#   - /etc/sysctl.d/99-nic-tuning.conf
#   - /etc/systemd/system/nic-tune-eno1.service  (re-applied bei jedem Boot)
#
# Aufruf:  sudo bash tune-nic-eno1.sh [IFACE]
#          IFACE default: eno1
#
set -euo pipefail

IFACE="${1:-eno1}"

if [[ $EUID -ne 0 ]]; then
    echo "Bitte als root ausfuehren (sudo)." >&2
    exit 1
fi

if ! ip link show "$IFACE" >/dev/null 2>&1; then
    echo "Interface $IFACE nicht gefunden." >&2
    exit 1
fi

echo "=== Tuning $IFACE ==="
echo

# ---------- 1) Snapshot vor Tuning ----------
STAMP="$(date +%Y%m%d-%H%M%S)"
SNAP="/var/log/nic-tune-${IFACE}-${STAMP}.before"
{
    echo "--- ethtool -l $IFACE ---"
    ethtool -l "$IFACE" 2>&1 || true
    echo "--- ethtool -g $IFACE ---"
    ethtool -g "$IFACE" 2>&1 || true
    echo "--- ethtool -S $IFACE | grep -E 'drop|miss|err|fifo' ---"
    ethtool -S "$IFACE" 2>&1 | grep -E 'drop|miss|err|fifo' || true
    echo "--- /proc/interrupts | grep $IFACE ---"
    grep -E "^\s*[0-9]+:.*$IFACE" /proc/interrupts || true
    echo "--- tc qdisc show dev $IFACE ---"
    tc qdisc show dev "$IFACE" 2>&1 || true
    echo "--- rps_cpus ---"
    for q in /sys/class/net/"$IFACE"/queues/rx-*/rps_cpus; do
        [[ -f "$q" ]] && echo "$q = $(cat "$q")"
    done
} > "$SNAP"
echo "Snapshot vor Tuning: $SNAP"
echo

# ---------- 2) Hardware-Queues maximieren (RSS) ----------
NCPU=$(nproc)
MAX_COMBINED=$(ethtool -l "$IFACE" 2>/dev/null | awk '/^Pre-set maximums:/{f=1} f && /Combined:/{print $2; exit}' || echo 1)
CUR_COMBINED=$(ethtool -l "$IFACE" 2>/dev/null | awk '/^Current hardware settings:/{f=1} f && /Combined:/{print $2; exit}' || echo 1)

echo "[RSS] Cores=$NCPU  HW-max combined=$MAX_COMBINED  aktuell=$CUR_COMBINED"
RSS_OK=0
if [[ "$MAX_COMBINED" =~ ^[0-9]+$ ]] && (( MAX_COMBINED > 1 )); then
    TARGET=$(( MAX_COMBINED < NCPU ? MAX_COMBINED : NCPU ))
    if (( TARGET > CUR_COMBINED )); then
        if ethtool -L "$IFACE" combined "$TARGET" 2>/dev/null; then
            echo "[RSS] -> combined=$TARGET gesetzt"
            RSS_OK=1
        else
            echo "[RSS] ethtool -L abgelehnt - fallback auf RPS"
        fi
    else
        echo "[RSS] bereits auf Maximum"
        RSS_OK=1
    fi
else
    echo "[RSS] Hardware unterstuetzt nur 1 Queue - fallback auf RPS"
fi

# ---------- 3) RPS-Fallback (Software RX-Verteilung) ----------
# Bitmask aller Cores in hex
MASK=$(printf '%x' $(( (1 << NCPU) - 1 )))
echo "[RPS] CPU-Maske=$MASK ($NCPU Cores)"
for q in /sys/class/net/"$IFACE"/queues/rx-*/rps_cpus; do
    [[ -f "$q" ]] || continue
    echo "$MASK" > "$q"
done
for q in /sys/class/net/"$IFACE"/queues/rx-*/rps_flow_cnt; do
    [[ -f "$q" ]] || continue
    echo 32768 > "$q"
done
sysctl -qw net.core.rps_sock_flow_entries=32768

# ---------- 4) Ring-Buffer maximieren ----------
RX_MAX=$(ethtool -g "$IFACE" 2>/dev/null | awk '/^Pre-set maximums:/{f=1} f && /^RX:/{print $2; exit}' || echo "")
TX_MAX=$(ethtool -g "$IFACE" 2>/dev/null | awk '/^Pre-set maximums:/{f=1} f && /^TX:/{print $2; exit}' || echo "")
if [[ "$RX_MAX" =~ ^[0-9]+$ ]] && [[ "$TX_MAX" =~ ^[0-9]+$ ]]; then
    echo "[RING] RX-max=$RX_MAX TX-max=$TX_MAX -> setze auf Maximum"
    ethtool -G "$IFACE" rx "$RX_MAX" tx "$TX_MAX" 2>/dev/null || \
        echo "[RING] ethtool -G abgelehnt (Treiber unterstuetzt es ggf. nicht)"
else
    echo "[RING] Maxima nicht lesbar - skip"
fi

# ---------- 5) qdisc fq_codel ----------
echo "[QDISC] -> fq_codel"
tc qdisc replace dev "$IFACE" root fq_codel || \
    echo "[QDISC] tc replace fehlgeschlagen"

# ---------- 6) sysctl-Tuning ----------
SYSCTL_FILE=/etc/sysctl.d/99-nic-tuning.conf
cat > "$SYSCTL_FILE" <<'EOF'
# Generated by tune-nic-eno1.sh
# Hoehere Backlog/Budget fuer hohe pps + RPS-Verteilung
net.core.netdev_max_backlog = 16384
net.core.netdev_budget = 600
net.core.netdev_budget_usecs = 8000
net.core.rps_sock_flow_entries = 32768

# TCP fuer viele kurzlebige Verbindungen
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
EOF
sysctl -q --system >/dev/null

# ---------- 7) systemd-Unit fuer Persistenz nach Reboot ----------
PERSIST_SCRIPT=/usr/local/sbin/nic-tune-${IFACE}.sh
cat > "$PERSIST_SCRIPT" <<EOF
#!/usr/bin/env bash
# Auto-generated by tune-nic-eno1.sh
set -e
IFACE=$IFACE
NCPU=\$(nproc)
MASK=\$(printf '%x' \$(( (1 << NCPU) - 1 )))

# RSS (falls Hardware unterstuetzt)
MAXC=\$(ethtool -l \$IFACE 2>/dev/null | awk '/^Pre-set maximums:/{f=1} f && /Combined:/{print \$2; exit}' || echo 1)
if [[ "\$MAXC" =~ ^[0-9]+\$ ]] && (( MAXC > 1 )); then
    T=\$(( MAXC < NCPU ? MAXC : NCPU ))
    ethtool -L \$IFACE combined \$T 2>/dev/null || true
fi

# RPS
for q in /sys/class/net/\$IFACE/queues/rx-*/rps_cpus; do
    [[ -f "\$q" ]] && echo \$MASK > "\$q"
done
for q in /sys/class/net/\$IFACE/queues/rx-*/rps_flow_cnt; do
    [[ -f "\$q" ]] && echo 32768 > "\$q"
done

# Ring
RXM=\$(ethtool -g \$IFACE 2>/dev/null | awk '/^Pre-set maximums:/{f=1} f && /^RX:/{print \$2; exit}')
TXM=\$(ethtool -g \$IFACE 2>/dev/null | awk '/^Pre-set maximums:/{f=1} f && /^TX:/{print \$2; exit}')
[[ "\$RXM" =~ ^[0-9]+\$ ]] && [[ "\$TXM" =~ ^[0-9]+\$ ]] && \
    ethtool -G \$IFACE rx \$RXM tx \$TXM 2>/dev/null || true

# qdisc
tc qdisc replace dev \$IFACE root fq_codel || true
EOF
chmod +x "$PERSIST_SCRIPT"

UNIT=/etc/systemd/system/nic-tune-${IFACE}.service
cat > "$UNIT" <<EOF
[Unit]
Description=NIC tuning for $IFACE (RSS/RPS + ring + fq_codel)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=$PERSIST_SCRIPT
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now "nic-tune-${IFACE}.service" >/dev/null

# ---------- 8) Snapshot nach Tuning ----------
SNAP_AFTER="/var/log/nic-tune-${IFACE}-${STAMP}.after"
{
    echo "--- ethtool -l $IFACE ---"
    ethtool -l "$IFACE" 2>&1 || true
    echo "--- ethtool -g $IFACE ---"
    ethtool -g "$IFACE" 2>&1 || true
    echo "--- tc qdisc show dev $IFACE ---"
    tc qdisc show dev "$IFACE" 2>&1 || true
    echo "--- rps_cpus ---"
    for q in /sys/class/net/"$IFACE"/queues/rx-*/rps_cpus; do
        [[ -f "$q" ]] && echo "$q = $(cat "$q")"
    done
} > "$SNAP_AFTER"

echo
echo "=== Fertig ==="
echo "Vorher:  $SNAP"
echo "Nachher: $SNAP_AFTER"
echo "Persistent: $UNIT  (enabled)"
echo
echo "Empfehlung: 1 Tag laufen lassen, dann vergleichen:"
echo "  ethtool -S $IFACE | grep -E 'drop|miss|err|fifo'"
echo "  cat /proc/interrupts | grep $IFACE   # Last-Verteilung pruefen"
echo "  mpstat -P ALL 5 3                    # softirq pro Core"
